// Dummy firebase_options.dart to allow the project to compile.
// In a real project, this file is generated by the FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPiQ37DTT0FLxWeEavFwXjqBWJJQ8r1l8',
    appId: '1:82275476229:web:be9dca2067a7def54b4d6c',
    messagingSenderId: '82275476229',
    projectId: 'week5-9b3b3',
    authDomain: 'week5-9b3b3.firebaseapp.com',
    storageBucket: 'week5-9b3b3.firebasestorage.app',
    measurementId: 'G-TB8NLTQHWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8xkzLuibwUjrWI6gpTDQMPqqpMXJDVM',
    appId: '1:82275476229:android:d48d8bfcedf4e1354b4d6c',
    messagingSenderId: '82275476229',
    projectId: 'week5-9b3b3',
    storageBucket: 'week5-9b3b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iYqkWKjsfQdoyI5H_3JeyIMB2-a8gQI',
    appId: '1:82275476229:ios:26fa367b0d7d1a834b4d6c',
    messagingSenderId: '82275476229',
    projectId: 'week5-9b3b3',
    storageBucket: 'week5-9b3b3.firebasestorage.app',
    iosClientId: '82275476229-hdgqt4m4hcksjejm09i6eodqvd89kn1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.week5Authentication',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-storage-bucket',
    iosBundleId: 'dummy-bundle-id',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-storage-bucket',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-storage-bucket',
  );
}