// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPC3mNwI02-4973-9jrMcMdRUOu3eihs',
    appId: '1:530243514963:web:cb1bda7dfa4884e4680ca6',
    messagingSenderId: '530243514963',
    projectId: 'campus-connect-92e90',
    authDomain: 'campus-connect-92e90.firebaseapp.com',
    storageBucket: 'campus-connect-92e90.firebasestorage.app',
    measurementId: 'G-W1T7XCETHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Mbp1s5mjmXbVEoGD0kHgRxje-zK6efI',
    appId: '1:530243514963:android:602477e2d96e8e49680ca6',
    messagingSenderId: '530243514963',
    projectId: 'campus-connect-92e90',
    storageBucket: 'campus-connect-92e90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnyFOA8lcDDUc1ixvQkvlL7V6ML_pNrL0',
    appId: '1:530243514963:ios:5ccafa1dbd44567d680ca6',
    messagingSenderId: '530243514963',
    projectId: 'campus-connect-92e90',
    storageBucket: 'campus-connect-92e90.firebasestorage.app',
    iosClientId: '530243514963-gltl8ghvuvgn1qm28j77ok41srbfrnfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnyFOA8lcDDUc1ixvQkvlL7V6ML_pNrL0',
    appId: '1:530243514963:ios:5ccafa1dbd44567d680ca6',
    messagingSenderId: '530243514963',
    projectId: 'campus-connect-92e90',
    storageBucket: 'campus-connect-92e90.firebasestorage.app',
    iosClientId: '530243514963-gltl8ghvuvgn1qm28j77ok41srbfrnfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPC3mNwI02-4973-9jrMcMdRUOu3eihs',
    appId: '1:530243514963:web:11df5a718d466e81680ca6',
    messagingSenderId: '530243514963',
    projectId: 'campus-connect-92e90',
    authDomain: 'campus-connect-92e90.firebaseapp.com',
    storageBucket: 'campus-connect-92e90.firebasestorage.app',
    measurementId: 'G-R2YVTEWHRN',
  );
}
